---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: namespace-watcher
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespace-watcher
rules:
- apiGroups: [""]
  resources: ["namespaces", "limitranges"]
  verbs: ["get", "watch", "list", "create", "delete"]
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: namespace-watcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: namespace-watcher
subjects:
- kind: ServiceAccount
  name: namespace-watcher
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: namespace-watcher
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: namespace-watcher
  template:
    metadata:
      labels:
        app: namespace-watcher
    spec:
      containers:
      - name: namespace-watcher
        image: wrkode/namespace-watcher:v0.9
        env:
        - name: CPU_LIMIT_MAX
          value: "2"
        - name: MEM_LIMIT_MAX
          value: "1Gi"
        - name: EPHEMERAL_STORAGE_MAX
          value: "4Gi"
        - name: CPU_LIMIT_MIN
          value: "1"
        - name: MEM_LIMIT_MIN
          value: "512Mi"
        - name: EPHEMERAL_STORAGE_MIN
          value: "2Gi"
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      restartPolicy: Always
      serviceAccountName: namespace-watcher